package com.jxc.struts2.pojo;

/**
 * Student generated by MyEclipse Persistence Tools
 */

public class Student implements java.io.Serializable {

	// Fields

	private Integer sid;

	private UserInfo userInfo;

	private String sname;

	private String sage;

	private String keMu;

	private Integer score;

	// Constructors

	/** default constructor */
	public Student() {
	}

	/** full constructor */
	public Student(UserInfo userInfo, String sname, String sage, String keMu,
			Integer score) {
		this.userInfo = userInfo;
		this.sname = sname;
		this.sage = sage;
		this.keMu = keMu;
		this.score = score;
	}

	// Property accessors

	public Integer getSid() {
		return this.sid;
	}

	public void setSid(Integer sid) {
		this.sid = sid;
	}

	public UserInfo getUserInfo() {
		return this.userInfo;
	}

	public void setUserInfo(UserInfo userInfo) {
		this.userInfo = userInfo;
	}

	public String getSname() {
		return this.sname;
	}

	public void setSname(String sname) {
		this.sname = sname;
	}

	public String getSage() {
		return this.sage;
	}

	public void setSage(String sage) {
		this.sage = sage;
	}

	public String getKeMu() {
		return this.keMu;
	}

	public void setKeMu(String keMu) {
		this.keMu = keMu;
	}

	public Integer getScore() {
		return this.score;
	}

	public void setScore(Integer score) {
		this.score = score;
	}

}